const cards = [
  {
    type: ["banking & finance"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/PAO-0@2x.jpg",
    heading: "Banking & Finance",
    text: "OCBC Pay Anyone",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["others"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/ECO-0@2x.jpg",
    heading: "Others",
    text: "Ecolab",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["others", "start-ups"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/KIWI-0@2x.jpg",
    heading: "Others, Start-ups",
    text: "KIWI Auto Marketplace",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["lifestyle"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/FURAMA-0@2x.jpg",
    heading: "Lifestyle",
    text: "Furama Hotels",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["transport & logistics"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/WTS-0@2x.jpg",
    heading: "Transport & Logistics",
    text: "Woodlands Transport",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["lifestyle", "retail & entertainment", "start-ups"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/RTT-0@2x.jpg",
    heading: "Lifestyle, Retail & Entertainment, Start-ups",
    text: "Ready To Travel (SATS)",
    className: "grid-column-2",
    whenHover: "hover--white",
    color: "text-black",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["lifestyle"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/YM-0@2x-1.jpg",
    heading: "Lifestyle",
    text: "Yoga Movement",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["retail & entertainment"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/DONKI-0@2x.jpg",
    heading: "Retail & Entertainment",
    text: "Don Don Donki",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["transport & logistics"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/TAP-0@2x.jpg",
    heading: "Transport & Logistics",
    text: "OCBC Pay Anyone",
    className: "",
    icons: ["https://www.codigo.co/img/ui/ico-app.svg"],
  },
  {
    type: ["others"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/FWD-0@2x.jpg",
    heading: "Others",
    text: "FWD Insurance",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["retail & entertainment"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/ISETAN-0@2x.jpg",
    heading: "Retail & Entertainment",
    text: "Isetan",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["retail & entertainment"],
    imgUrl: "https://cdn.codigo.co/uploads/2021/04/HBO-0@2x-2.jpg",
    heading: "Retail & Entertainment",
    text: "HBO GO",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["telco"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/12/MYR.jpg",
    heading: "Telco",
    text: "MyRepublic Mobile",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["transport & logistics"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/08/CDG-2-1.jpg",
    heading: "Transport & Logistics",
    text: "ComfortDelGro",
    className: "",
    whenHover: "hover--white",
    color: "text-black",
    icons: ["https://www.codigo.co/img/ui/ico-app.svg"],
  },
  {
    type: ["retail & entertainment"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/04/711.jpg",
    heading: "Retail & Entertainment",
    text: "7Rewards",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
    ],
  },
  {
    type: ["retail & entertainment"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/08/FPOL.jpg",
    heading: "Retail & Entainment",
    text: "FairPrice Online",
    className: "grid-column-2",
    icons: ["https://www.codigo.co/img/ui/ico-uiux.svg"],
  },
  {
    type: ["retail & entertainment"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/12/ck.jpg",
    heading: "Retail & Entertainment",
    text: "Charles & Keith / Pedro",
    className: "grid-column-2",
    whenHover: "hover--white",
    color: "text-black",
    icons: ["https://www.codigo.co/img/ui/ico-app.svg"],
  },
  {
    type: ["retail & entertainment"],
    imgUrl:
      "https://cdn.codigo.co/uploads/2018/11/thumbnail-justice_league@2x.jpg",
    heading: "Retail & Entertainment",
    text: "Justice League",
    className: "grid-column-2",
    icons: ["https://www.codigo.co/img/ui/ico-app.svg"],
  },
  {
    type: ["healthcare"],
    imgUrl:
      "https://cdn.codigo.co/uploads/2018/11/fullerton-health-thumbnail@2x.jpg",
    heading: "Healthcare",
    text: "Fullerton Health",
    className: "",
    icons: ["https://www.codigo.co/img/ui/ico-app.svg"],
  },
  {
    type: ["lifestyle"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/11/skypremium-thumbnail@2x.jpg",
    heading: "Lifestyle",
    text: "Sky Premium",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
    ],
  },
  {
    type: ["lifestyle"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/12/TSingapore-thumbnail@2x.jpg",
    heading: "Lifestyle",
    text: "T Singapore",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
    ],
  },
  {
    type: ["transport & logistics"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/12/singpost-thumbnail@2x.jpg",
    heading: "Transport & Logistics",
    text: "SingPost",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-uiux.svg",
    ],
  },
  {
    type: ["food & beverage", "co-incubation", "start-ups"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/12/dineinn.jpg",
    heading: "Co-incubation, Start-ups, Food & Beverage",
    text: "OCBC Pay Anyone",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
    ],
  },
  {
    type: ["transport & logistics"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/11/siemens.jpg",
    heading: "Transport & Logistics",
    text: "Siemens Engineering",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
    ],
  },
  {
    type: [""],
    imgUrl: "https://cdn.codigo.co/uploads/2018/12/f1.jpg",
    heading: " ",
    text: "Singapore Grand Prix",
    className: "",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
    ],
  },
  {
    type: ["tranport & logistics", "co-incubation", "start-ups"],
    imgUrl: "https://cdn.codigo.co/uploads/2018/12/FF-1.jpg",
    heading: "Transport & Logistics, Co-incubation, Start-ups",
    text: "FastFast Delivery",
    className: "grid-column-2",
    icons: [
      "https://www.codigo.co/img/ui/ico-app.svg",
      "https://www.codigo.co/img/ui/ico-web.svg",
      "https://www.codigo.co/img/ui/ico-cms.svg",
    ],
  },
  {
    type: ["food & beverage"],
    imgUrl: " https://cdn.codigo.co/uploads/2018/12/mc-cafe-thumbnail@2x.jpg",
    heading: "Food & Beverage",
    text: "McDonald's",
    className: "",
    icons: ["https://www.codigo.co/img/ui/ico-app.svg"],
  },
];

export default cards;
